In [60]:
def welcome_message():
  print("Hello User")

In [61]:
welcome_message()

Hello User

In [62]:
def welcome_message(user=None):
  """
  Joy Bangla
  """
  print(f"Hello {user}")

In [63]:
welcome_message()

Hello None

In [64]:
help(print)
help(welcome_message)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

Help on function welcome_message in module __main__:

welcome_message(user=None)
    Joy Bangla

In [65]:
def adder(*pa):
  print(pa)
  for _ in pa:
    print(_)

In [66]:
adder(1,2,3,4,5)

(1, 2, 3, 4, 5)
1
2
3
4
5

In [67]:
def adder(**kwargs):
  print(kwargs)
  for key, value in kwargs.items():
    print(f"{key}: {value}")

adder(a = 5, b = 3, c = "awer")

{'a': 5, 'b': 3, 'c': 'awer'}
a: 5
b: 3
c: awer

In [68]:
print(type(adder(a = 5, b = 3, c = "awer")))

{'a': 5, 'b': 3, 'c': 'awer'}
a: 5
b: 3
c: awer
<class 'NoneType'>

# iterator and generator in python

In [69]:
s = {10,20,30,40,50,60}
print(s)
s_iter = iter(s)
print(s_iter)
print(type(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))

for i in s: print(i)

{50, 20, 40, 10, 60, 30}
<set_iterator object at 0x7f8fc02c4580>
<class 'set_iterator'>
50
20
40
10
60
30
50
20
40
10
60
30

#Generator

In [70]:
lst = [x for x in range(100)]
def dataloader(chunk_size, lst):
  for i in range(0, len(lst), chunk_size):
    yield lst[i: i+chunk_size]

x = dataloader(5, lst)
print(x)
print(type(x))
for i in x: print(i)

<generator object dataloader at 0x7f8fc06a7790>
<class 'generator'>
[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]
[10, 11, 12, 13, 14]
[15, 16, 17, 18, 19]
[20, 21, 22, 23, 24]
[25, 26, 27, 28, 29]
[30, 31, 32, 33, 34]
[35, 36, 37, 38, 39]
[40, 41, 42, 43, 44]
[45, 46, 47, 48, 49]
[50, 51, 52, 53, 54]
[55, 56, 57, 58, 59]
[60, 61, 62, 63, 64]
[65, 66, 67, 68, 69]
[70, 71, 72, 73, 74]
[75, 76, 77, 78, 79]
[80, 81, 82, 83, 84]
[85, 86, 87, 88, 89]
[90, 91, 92, 93, 94]
[95, 96, 97, 98, 99]

# Lambda

In [71]:
lst = [x for x in range(100)]
squared_lst = [i**2 for i in lst]
print(squared_lst[:10]) # Print first 10 elements to verify

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [72]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use a lambda function with filter to get only even numbers
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))

print("Original list:", numbers)
print("Filtered list (even numbers):", even_numbers)

Original list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Filtered list (even numbers): [2, 4, 6, 8, 10]

In [73]:
import pandas as pd
df = pd.DataFrame({'temperature (F)': [32, 212, 98.6, 68]})
df
df['temperature (C)'] = df['temperature (F)'].apply(lambda x : 5*(x-32)/9)
df

   temperature (F)  temperature (C)
0             32.0              0.0
1            212.0            100.0
2             98.6             37.0
3             68.0             20.0

In [74]:
df = pd.DataFrame({'A': [1,2,3,4,5], 'B': [2,3,4,5, 2]})
df
df['A'] = df['A'].map(lambda x : x**.5)
df
df['C'] = df['A'].map(lambda x: x**3)
df

          A  B          C
0  1.000000  2   1.000000
1  1.414214  3   2.828427
2  1.732051  4   5.196152
3  2.000000  5   8.000000
4  2.236068  2  11.180340

In [75]:
df['high_value'] = df['C'].apply(lambda x : 1 if x>2 else 0)
df

          A  B          C  high_value
0  1.000000  2   1.000000           0
1  1.414214  3   2.828427           1
2  1.732051  4   5.196152           1
3  2.000000  5   8.000000           1
4  2.236068  2  11.180340           1